### PR TITLE
Spoon snapshot

### PR DESCRIPTION
**Pull request by lebzuch**
Android Studio 3.0 didn't work with spoon 1.* so I handle latest snapshot of spoon client.

### CODE REVIEW

**Comment by jraska** [comment]
Nice work thanks! As I see the project is a bit deprecated so I will try to submit update PR for the emulator on Travis, which is now failing.

**Comment by IrenaMystic** [comment]
I am trying to implement FalconSpoon in my project, but it is not compatible with spoon's latest version. I saw that there is a PR on the matter, so my question is when is going to be merged?

**Comment by jraska** [comment]
Hello @IrenaMystic, I got no response from lebzuch since I commented, because there are small changes required.

I might do them by myself once I find time for it, but if you are faster please feel free to copy the repo from lebzuch and do these changes.

Thanks for the comment I will try to do the changes, but it can take few days I'm bit busy these days.

**Comment by lebzuch** [comment]
Hi @jraska,
I don't know what changes you are talking about. You just comment that 
> I will try to submit update PR for the emulator on Travis
so I'm waiting for it :)

**Comment by jraska** [comment]
FalconSpoonRule.java has a comment :)

**Comment by lebzuch** [comment]
I don't know if I'm blind or sth but I cannot se it...

**Comment by jraska** [comment]
Wow! My bad! I did the comment, submitted and then there is extra step clicking the submit button again. Sorry for that!

**Comment by jraska** [comment]
Awesome! Thank you very much. 👍  Whole Travis build seems broken by time so I will accept the PR now, which will force me to update the tests and build files soon probably over weekend.

There will be new release of FalconSpoon after that with major version update.

Thanks again for help.

**Comment by jraska** [comment]
@lebzuch , @IrenaMystic Version 2.0.0 released.

**Pull request merged**
